-- ============================================================================
-- VIP AUTOMATION SYSTEM - ENTERPRISE SUPABASE POSTGRESQL SCHEMA
-- ============================================================================
-- Fully normalized, modular, and scalable schema architecture for:
--   1. Multi-Bot Payment Registry & Per-Bot VIP Packages
--   2. Real-Time SociaBuzz QRIS Payment Processing & Auto-Invites
--   3. 50% Referral Commission System & E-Wallet Withdrawals
--   4. Rich Media Daily Broadcast Scheduler
-- ============================================================================

-- ============================================================================
-- SECTION 1: SYSTEM SETTINGS & BOT REGISTRY
-- ============================================================================

-- Key-value table for global runtime settings (vip_chat_id, log_chat_id, broadcast_time, etc.)
CREATE TABLE IF NOT EXISTS public.vip_bot_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Registry table for Multi-Bot Payment Clients
CREATE TABLE IF NOT EXISTS public.vip_payment_bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_token TEXT NOT NULL UNIQUE,
    bot_username TEXT NOT NULL DEFAULT '',
    bot_name TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 2: USER PROFILES & REFERRAL NETWORK
-- ============================================================================

-- Stores Telegram users, unique referral codes, balances, and counts
CREATE TABLE IF NOT EXISTS public.vip_users (
    user_id BIGINT PRIMARY KEY,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    referral_code TEXT NOT NULL UNIQUE,
    invited_by_user_id BIGINT REFERENCES public.vip_users(user_id) ON DELETE SET NULL,
    balance INTEGER NOT NULL DEFAULT 0 CHECK (balance >= 0),
    pending_referrals INTEGER NOT NULL DEFAULT 0 CHECK (pending_referrals >= 0),
    successful_referrals INTEGER NOT NULL DEFAULT 0 CHECK (successful_referrals >= 0),
    is_bot BOOLEAN NOT NULL DEFAULT false,
    last_broadcast_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 3: VIP PACKAGES & PER-BOT ISOLATION
-- ============================================================================

-- Stores active VIP Access Packages, scoped per Bot Payment or globally
CREATE TABLE IF NOT EXISTS public.vip_packages (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    vip_chat_id BIGINT NOT NULL,
    amount INTEGER NOT NULL CHECK (amount >= 1000 AND amount <= 10000000),
    bot_username TEXT NOT NULL DEFAULT '',
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 4: PAYMENT ORDERS & QRIS TRANSACTIONS
-- ============================================================================

-- Stores QRIS orders generated via SociaBuzz API Gateway
CREATE TABLE IF NOT EXISTS public.vip_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.vip_users(user_id) ON DELETE CASCADE,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    bot_username TEXT NOT NULL DEFAULT '',
    package_code TEXT NOT NULL DEFAULT '',
    package_name TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    vip_chat_id BIGINT,
    invite_expire_hours INTEGER NOT NULL DEFAULT 0,
    public_invoice_id TEXT NOT NULL UNIQUE,
    order_id TEXT NOT NULL UNIQUE,
    payment_url TEXT NOT NULL,
    inv_id TEXT NOT NULL UNIQUE,
    amount INTEGER NOT NULL CHECK (amount > 0),
    status TEXT NOT NULL CHECK (
        status IN (
            'pending',
            'processing_paid',
            'invite_error',
            'processing_delivery',
            'delivery_error',
            'delivery_blocked',
            'paid',
            'failed_or_expired',
            'unknown',
            'poll_error',
            'timeout'
        )
    ),
    buyer_name TEXT NOT NULL,
    buyer_email TEXT NOT NULL,
    qris_amount TEXT NOT NULL DEFAULT '',
    qris_expires TEXT NOT NULL DEFAULT '',
    qris_chat_id BIGINT,
    qris_message_id BIGINT,
    next_check_at TIMESTAMPTZ,
    poll_attempts INTEGER NOT NULL DEFAULT 0,
    last_polled_at TIMESTAMPTZ,
    invite_link TEXT,
    invite_expires_at TIMESTAMPTZ,
    referral_id BIGINT,
    referrer_user_id BIGINT REFERENCES public.vip_users(user_id) ON DELETE SET NULL,
    error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 5: REFERRAL EARNINGS & FINANCIAL WITHDRAWALS
-- ============================================================================

-- Tracks referral invitations and 50% commission crediting
CREATE TABLE IF NOT EXISTS public.vip_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id BIGINT NOT NULL REFERENCES public.vip_users(user_id) ON DELETE CASCADE,
    referrer_code TEXT NOT NULL,
    invited_user_id BIGINT NOT NULL UNIQUE REFERENCES public.vip_users(user_id) ON DELETE CASCADE,
    invited_username TEXT NOT NULL DEFAULT '',
    invited_full_name TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    payment_inv_id TEXT,
    package_code TEXT NOT NULL DEFAULT '',
    package_amount INTEGER NOT NULL DEFAULT 0,
    commission_amount INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tracks user withdrawal requests to Dana/Ovo/Gopay/Bank
CREATE TABLE IF NOT EXISTS public.vip_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.vip_users(user_id) ON DELETE CASCADE,
    username TEXT NOT NULL DEFAULT '',
    full_name TEXT NOT NULL DEFAULT '',
    amount INTEGER NOT NULL CHECK (amount >= 10000),
    phone TEXT NOT NULL,
    wallet_name TEXT NOT NULL,
    account_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rejected')),
    admin_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 6: BROADCAST SCHEDULER
-- ============================================================================

-- Stores active daily broadcast messages (text, photo, video)
CREATE TABLE IF NOT EXISTS public.vip_broadcast_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_text TEXT NOT NULL DEFAULT '',
    media_telegram_file_id TEXT NOT NULL DEFAULT '',
    media_type TEXT NOT NULL DEFAULT '',
    entities_json TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- SECTION 7: ATOMIC PL/pgSQL STORED PROCEDURES
-- ============================================================================

-- Atomically increment pending referral count for inviter
CREATE OR REPLACE FUNCTION public.vip_increment_pending_referral(p_user_id BIGINT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET pending_referrals = pending_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

-- Atomically credit 50% referral commission to balance
CREATE OR REPLACE FUNCTION public.vip_credit_referral_commission(p_user_id BIGINT, p_amount INTEGER)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        pending_referrals = GREATEST(pending_referrals - 1, 0),
        successful_referrals = successful_referrals + 1,
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

-- Atomically credit balance (used for withdrawal refunds)
CREATE OR REPLACE FUNCTION public.vip_credit_balance(p_user_id BIGINT, p_amount INTEGER)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    UPDATE public.vip_users
    SET balance = balance + GREATEST(p_amount, 0),
        updated_at = now()
    WHERE user_id = p_user_id;
$$;

-- Atomically create withdrawal request and deduct balance
CREATE OR REPLACE FUNCTION public.vip_create_withdrawal(
    p_user_id BIGINT,
    p_username TEXT,
    p_full_name TEXT,
    p_amount INTEGER,
    p_phone TEXT,
    p_wallet_name TEXT,
    p_account_name TEXT
)
RETURNS SETOF public.vip_withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    created public.vip_withdrawals;
BEGIN
    IF p_amount < 10000 THEN
        RETURN;
    END IF;

    UPDATE public.vip_users
    SET balance = balance - p_amount,
        phone = p_phone,
        updated_at = now()
    WHERE user_id = p_user_id
      AND balance >= p_amount;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    INSERT INTO public.vip_withdrawals (
        user_id,
        username,
        full_name,
        amount,
        phone,
        wallet_name,
        account_name,
        status,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        p_username,
        p_full_name,
        p_amount,
        p_phone,
        p_wallet_name,
        p_account_name,
        'pending',
        now(),
        now()
    ) RETURNING * INTO created;

    RETURN NEXT created;
END;
$$;

-- ============================================================================
-- SECTION 8: INDEXES, ROW LEVEL SECURITY (RLS) & PERMISSIONS
-- ============================================================================

-- Performance & Query Optimization Indexes
CREATE INDEX IF NOT EXISTS idx_vip_payments_user_status ON public.vip_payments (user_id, status, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_payments_status_id ON public.vip_payments (status, id ASC);
CREATE INDEX IF NOT EXISTS idx_vip_payments_next_check ON public.vip_payments (next_check_at ASC, id ASC) WHERE status IN ('pending', 'invite_error', 'delivery_error');
CREATE INDEX IF NOT EXISTS idx_vip_payments_package_code ON public.vip_payments (package_code);

CREATE UNIQUE INDEX IF NOT EXISTS idx_vip_payments_one_active_per_user ON public.vip_payments (user_id) WHERE status IN ('pending', 'processing_paid', 'invite_error', 'processing_delivery', 'delivery_error');

CREATE INDEX IF NOT EXISTS idx_vip_users_referral_code ON public.vip_users (referral_code);
CREATE INDEX IF NOT EXISTS idx_vip_users_invited_by ON public.vip_users (invited_by_user_id);
CREATE INDEX IF NOT EXISTS idx_vip_users_broadcast_order ON public.vip_users (is_bot, last_broadcast_at ASC NULLS FIRST, user_id);

CREATE INDEX IF NOT EXISTS idx_vip_broadcast_messages_active ON public.vip_broadcast_messages (is_active, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_referrals_referrer_status ON public.vip_referrals (referrer_user_id, status, id DESC);
CREATE INDEX IF NOT EXISTS idx_vip_referrals_referrer_code ON public.vip_referrals (referrer_code);
CREATE INDEX IF NOT EXISTS idx_vip_withdrawals_user_status ON public.vip_withdrawals (user_id, status, id DESC);

-- Row Level Security (RLS) Enforcement
ALTER TABLE public.vip_bot_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_payment_bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_broadcast_messages ENABLE ROW LEVEL SECURITY;

-- Service Role Grant Policies
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

REVOKE ALL ON FUNCTION public.vip_increment_pending_referral(BIGINT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.vip_increment_pending_referral(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_referral_commission(BIGINT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_credit_balance(BIGINT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.vip_create_withdrawal(BIGINT, TEXT, TEXT, INTEGER, TEXT, TEXT, TEXT) TO service_role;
